---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 59793123-ZipryHd2J1GOVQkcVPB1sPwBZRzFrAk4BWtEi6Okc
:oauth_secret: i9yA7Cek3aldJoXPDcg3W6C5cC9JRmCFxbNIke8W1A
